### ISSUE TITLE
Add support for Pine Script

### ISSUE THREAD

**Issue by ozum** [pouyakary/comment#24]
Hi,

Thanks for the addon. It would be great if it supports Pine Script.

File extension: *.pine
Comment Syntax: `//`

Example:

```pine
// Comment
var grpAdx = "Trend"
```

Kind Regards,

**Comment by pouyakary** [comment]
Funny thing is that I used to be PineScript compiler engineer for almost two years and forgot to have it in the list :)))))

**Comment by ozum** [comment]
It really is indeed :))))))
